// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/aside/aside.vue')['default']
    ColSetting: typeof import('./src/components/table/components/colSetting.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Logo: typeof import('./src/components/aside/logo.vue')['default']
    MenuVertical: typeof import('./src/components/aside/menuVertical.vue')['default']
    Message: typeof import('./src/components/navBar/message.vue')['default']
    NavMenus: typeof import('./src/components/navBar/navMenus.vue')['default']
    NavTabs: typeof import('./src/components/navBar/navTabs.vue')['default']
    PageHeader: typeof import('./src/components/pageHeader.vue')['default']
    Pagination: typeof import('./src/components/table/components/pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tree: typeof import('./src/components/aside/tree.vue')['default']
    Uploading: typeof import('./src/components/uploading/index.vue')['default']
  }
}
